export const FOCUS_AREAS = {
  TRANSACTION_GAP: {
    id: 'transaction_gap',
    label: 'Payment Friction (Transactional Gap)',
    keywords: [
      'charged but',
      'refund stuck',
      'double charge',
      'checkout spinning',
      'no refund',
      'charged twice',
      'refund failed',
      'payment not showing',
      'payment missing',
      'paid for',
      'never got',
    ],
    description: 'Money moved but value or reconciliation failed.',
  },
  FALSE_HEALTH: {
    id: 'false_health',
    label: 'System Ghosting (False Health)',
    keywords: [
      'dashboard green but',
      'dashboard shows green but',
      'logs say success',
      'logs show success but',
      'shows delivered',
      'says delivered but',
      'not in bank',
      'status page says up but',
      'metrics say',
      'monitoring says',
    ],
    description: 'Tooling reports healthy while customers see failure.',
  },
  BLAST_RADIUS: {
    id: 'blast_radius',
    label: 'The V4 Cliff (Update Blast Radius)',
    keywords: [
      'elementor v4',
      'wp update',
      'breaking change',
      'crashed after upgrade',
      'update broke',
      'v4',
      'after updating',
      'latest version',
      'stopped working',
    ],
    description: 'Product updates causing regression.',
  },
  API_DRIFT: {
    id: 'api_drift',
    label: 'API / Webhook Drift',
    keywords: [
      'deprecated',
      'webhook',
      'webhook fail',
      'api changed',
      'rate limit',
      'changed without notice',
    ],
    description: 'Third-party infrastructure changed; integrations break.',
  },
  SUPPORT_FAILURE: {
    id: 'support_failure',
    label: 'Support Black Hole',
    keywords: [
      'no answer for days',
      'copy paste reply',
      'copy-paste',
      'support is useless',
      'useless support',
      'no response',
      'ignored',
      'happiness engineer',
    ],
    description: 'Vendor support failed; user ready to leave stack.',
  },
} as const;

export type FocusAreaId = (typeof FOCUS_AREAS)[keyof typeof FOCUS_AREAS]['id'];
