export const FOCUS_AREAS = {
  TRANSACTION_GAP: {
    id: 'transaction_gap',
    label: 'Payment Friction (Transactional Gap)',
    keywords: [
      'charged but',
      'refund stuck',
      'double charge',
      'checkout spinning',
      'checkout broken',
      'no refund',
      'charged twice',
      'refund failed',
      'payment not showing',
      'payment missing',
      'paid for',
      'never got',
      'chargeback',
      'disputed charge',
      'money disappeared',
      'transaction failed',
      'payment declined',
      'card declined',
      'paypal holding',
      'payout delayed',
      'subscription charged',
      'billed twice',
      'stripe dashboard',
      'orders not syncing',
      'cart abandoned',
      'failed payment',
      'money stuck',
      'revenue missing',
      'invoice wrong',
      'duplicate charge',
      'wallet shows wrong',
      'woocommerce checkout',
      'charged but order',
      'payment complete but order',
      'order stuck on pending',
      'order pending forever',
      'cart empty at checkout',
      'paypal pending order',
      'stripe paid but woocommerce',
      'subscription renewal failed',
      'wc payments',
    ],
    description: 'Money moved but value or reconciliation failed.',
  },
  FALSE_HEALTH: {
    id: 'false_health',
    label: 'System Ghosting (False Health)',
    keywords: [
      'dashboard green but',
      'dashboard shows green but',
      'logs say success',
      'logs show success but',
      'shows delivered',
      'says delivered but',
      'not in bank',
      'status page says up but',
      'metrics say',
      'monitoring says',
      'analytics wrong',
      'reports dont match',
      "reports don't match",
      'conversion mismatch',
      'tracking shows',
      'pixel fires but',
      'email says sent',
      'never arrived',
      'inventory wrong',
      'stock count wrong',
      'sync says complete',
      'ledger doesnt match',
      "ledger doesn't match",
      'shows paid but',
      'crm says',
      'bank doesnt show',
      "bank doesn't show",
      'false positive',
      'everything looks fine but',
      'woocommerce says',
      'backend shows paid',
      'stripe shows paid but',
      'order completed but never',
      'shows processing but',
      'stock wrong woocommerce',
      'inventory sync wrong',
      'wc admin shows',
    ],
    description: 'Tooling reports healthy while customers see failure.',
  },
  BLAST_RADIUS: {
    id: 'blast_radius',
    label: 'The V4 Cliff (Update Blast Radius)',
    keywords: [
      'elementor v4',
      'wp update',
      'woocommerce update',
      'plugin update broke',
      'breaking change',
      'crashed after upgrade',
      'update broke',
      'after updating',
      'latest version',
      'stopped working',
      'fatal error',
      'white screen',
      'theme broke',
      'plugin conflict',
      'automatic update',
      'rolled out',
      'php update',
      'shopify update',
      'app update broke',
      'deprecated function',
      'works on staging',
      'broke in production',
      'was fine yesterday',
      'critical error wordpress',
      'critical error on this website',
      'blocks checkout',
      'classic checkout',
      'hpos',
      'high-performance order storage',
      'elementor conflict',
      'elementor broke',
      'wp-admin blank',
      'wp-admin fatal',
      'php fatal error',
      'memory limit wordpress',
      'plugin conflict woocommerce',
      'theme conflict woocommerce',
    ],
    description: 'Product updates causing regression.',
  },
  API_DRIFT: {
    id: 'api_drift',
    label: 'API / Webhook Drift',
    keywords: [
      'deprecated',
      'webhook',
      'webhook fail',
      'webhook not firing',
      'api changed',
      'rate limit',
      'changed without notice',
      'oauth',
      'integration broke',
      'sync stopped',
      '401',
      '403',
      'invalid signature',
      'api key invalid',
      'payload changed',
      'endpoint changed',
      'zapier failed',
      'make integration',
      'n8n',
      'stripe webhook',
      'paypal ipn',
      'retry storm',
      'timeout',
      'third party api',
      '/wp-json/',
      'wp-json error',
      'woocommerce webhook',
      'woocommerce rest api',
      'application password',
      'square woocommerce',
      'klarna woocommerce',
      'action scheduler',
      'legacy checkout ajax',
    ],
    description: 'Third-party infrastructure changed; integrations break.',
  },
  SUPPORT_FAILURE: {
    id: 'support_failure',
    label: 'Support Black Hole',
    keywords: [
      'no answer for days',
      'copy paste reply',
      'copy-paste',
      'support is useless',
      'useless support',
      'no response',
      'ignored',
      'happiness engineer',
      'ticket closed',
      'cant reach a human',
      "can't reach a human",
      'chat bot loop',
      'vendor ghosted',
      'hosting support',
      'theme support',
      'plugin author',
      'still waiting',
      'radio silence',
      'nobody answers',
      'closed my ticket',
      'unresolved',
      'weeks and no reply',
      'same canned response',
      'escalated nowhere',
      'automattic',
      'woocommerce support',
      'wordpress.org support',
      'codecanyon',
      'envato support',
      'themeforest support',
      'plugin author wont',
      "plugin author won't",
    ],
    description: 'Vendor support failed; user ready to leave stack.',
  },
} as const;

export type FocusAreaId = (typeof FOCUS_AREAS)[keyof typeof FOCUS_AREAS]['id'];
